# Generated by Django 5.1.5 on 2025-01-31 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=200)),
                ('dealer_info', models.CharField(max_length=200)),
                ('target_lat', models.CharField(max_length=200)),
                ('target_lon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=None)),
                ('agentt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
                ('dealerr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dealer')),
            ],
        ),
    ]
