# Generated by Django 5.1.5 on 2025-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='track_ID',
            field=models.CharField(default=123, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
