# Generated by Django 5.1.5 on 2025-01-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_track_assigned_track_track_id_alter_agent_agent_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='date',
        ),
    ]
